Repository thiagolinch/modacadFront, pull requests merged in 2024-12, with the labels that each got.

#42 FEAT: delete post button
  src/pages/dashboard/post-editor/components/CardBasicInfo.tsx
  src/shared/api/posts/PostsService.ts
Labels: enhancement

#44 FEAT: snnipets google e facebook conforme o design
  package.json
  src/pages/dashboard/post-editor/components/CardBasicInfo.tsx
  src/pages/dashboard/post-editor/components/snnipets/FaceSnnipetPreviewl.tsx
  src/pages/dashboard/post-editor/components/snnipets/GoogleSnnipetsPreview.tsx
  yarn.lock
Labels: enhancement

#46 FEAT: limitar escrita nos campos definidos pelo design da Telma
  src/pages/admin/tags/components/CreateTag.tsx
  src/pages/dashboard/post-editor/components/CardBasicInfo.tsx
Labels: enhancement

#50 Feat/layout listagem de posts
  src/pages/admin/team/PageTeam.tsx
  src/pages/admin/team/components/CreateMember.tsx
  src/pages/admin/team/components/InviteNewMember.tsx
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/post-editor/components/CardBasicInfo.tsx
  src/routes/index.tsx
  src/shared/api/posts/PostsService.ts
  src/shared/api/users/UserServices.ts
  src/shared/components/menu-lateral/MenuLateral.tsx
  src/shared/components/ui/dropdown-menu/DropdownMenu.tsx
  src/shared/services/postOptions.ts
  src/shared/services/userOptions.ts
Labels: bug, enhancement

#51 Hotfix/correcoes para producao
  src/pages/dashboard/post-editor/components/CardBasicInfo.tsx
  src/pages/home/Home.tsx
  src/pages/posts/PopularPosts.tsx
  src/pages/posts/PublishedPills.tsx
  src/shared/components/ScrollPilulasMDC.tsx
  src/shared/components/ScrollTextoMDC.tsx
  src/shared/components/ScrollTextoMaisLidos.tsx
  src/shared/components/last-post.tsx
Labels: bug

#55 FIX: url duplicando o protocolo "https" ao enviar ao back
  src/pages/dashboard/post-editor/components/CardBasicInfo.tsx
  src/pages/dashboard/post-editor/components/snnipets/CardTagInfo.tsx
Labels: bug

#58 hotFIX: botao de novo post nao estava levando para o postEditor.
  src/pages/dashboard/Dashboard.tsx
Labels: bug

#60 ajuste de pasta, botao excluir ja retorna ao card inicial.
  src/pages/dashboard/post-editor/components/CardBasicInfo.tsx
  src/pages/dashboard/post-editor/components/CardTagInfo.tsx
Labels: bug

#63 56 feat paginas de posts
  src/assets/css/tiptap.css
  src/pages/posts/PostDetails.tsx
  src/pages/posts/pilula/PillDetails.tsx
  src/pages/posts/pilula/components/PillDesktopHeader.tsx
  src/pages/posts/pilula/components/PillMobileHeader.tsx
  src/pages/posts/textos/PopularPosts.tsx
  src/pages/posts/textos/PostDetails.tsx
  src/pages/posts/textos/PublishedPosts.tsx
  src/pages/posts/textos/components/PostDesktopHeader.tsx
  src/pages/posts/textos/components/PostMobileHeader.tsx
  src/routes/index.tsx
  src/types/global.d.ts
Labels: enhancement

#64 Feat/pagina home
  src/assets/imgs/default_image_300_300.jpg
  src/pages/home/Home.tsx
  src/pages/posts/page-category-post/PageCategoryPost.tsx
  src/pages/posts/textos/PopularPosts.tsx
  src/pages/posts/textos/PublishedPosts.tsx
  src/routes/index.tsx
  src/shared/components/footer.tsx
  src/shared/components/header/public-header/DrawerLateral.tsx
  src/shared/components/header/public-header/PublicHeader.tsx
  src/shared/components/posts/featured-post/FeaturedPost.tsx
  src/shared/components/posts/post-presentation/PostPresentation.tsx
  src/shared/components/posts/post-presentation/card/PostCard.tsx
  src/shared/components/posts/post-presentation/presentation/PostGrid.tsx
  src/shared/components/posts/post-presentation/presentation/PostList.tsx
  src/shared/components/search-dialog/SearchDialog.tsx
Labels: enhancement

#66 65 fix fonts do editor
  src/assets/css/tiptap.css
  src/pages/dashboard/post-editor/PostEditor.tsx
  src/pages/posts/pilula/PillDetails.tsx
  src/pages/posts/textos/PostDetails.tsx
Labels: enhancement

#69 FEAT: preview da url das tags nos cards.
  src/assets/tiptapExtensao/embed.tsx
  src/pages/admin/tags/components/CreateTag.tsx
  src/pages/dashboard/post-editor/components/CardTagInfo.tsx
Labels: enhancement

#74 Feat/textos no banner
  src/pages/home/Home.tsx
  src/pages/posts/pilula/components/PillDesktopHeader.tsx
  src/pages/posts/pilula/components/PillMobileHeader.tsx
  src/pages/posts/textos/components/PostDesktopHeader.tsx
  src/pages/posts/textos/components/PostMobileHeader.tsx
  src/shared/components/cta-app/CTAApp.tsx
  src/shared/components/footer.tsx
  src/shared/components/reagindBox.tsx
Labels: enhancement
